version: '3.3'

services:
 php:
  build:
   context: .
   dockerfile: dockerfile
  container_name: php73
  depends_on:
   - db
  image: php:7.3-apache
  volumes:
   - ./php:/var/www/html/
  ports:
   - 8000:80
 db:
  container_name: mysql8
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: bzhsec
   MYSQL_USER: user1
   MYSQL_PASSWORD: root
  ports:
   - 8001:80
 phpmya:
  image: phpmyadmin/phpmyadmin:latest
  container_name: phpmyadmin
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: db
   PMA_USER: root
   PMA_PASSWORD: root
   UPLOAD_LIMIT: 20M
  ports:
   - 8002:80